In [1]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.  Downloading libclang-14.0.1-py2.py3-none-win_amd64.whl (14.2 MB)


ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

basemap 1.3.0 requires numpy<1.22,>=1.16; python_version >= "3.5", but you'll have numpy 1.23.0 which is incompatible.



  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4835 sha256=ab03b134f762ddd1f128e8d8f9638df1913d7268bad7e584760d57a16d978d8f
  Stored in directory: c:\users\pstrz\appdata\local\pip\cache\wheels\a0\16\9c\5473df82468f958445479c59e784896fa24f4a5fc024b0f501
Successfully built termcolor
  Attempting uninstall: numpy
    Found existing installation: numpy 1.19.2
    Uninstalling numpy-1.19.2:
      Successfully uninstalled numpy-1.19.2
  Attempting uninstall: importlib-metadata
    Found existing installation: importlib-metadata 2.0.0
    Uninstalling importlib-metadata-2.0.0:
      Successfully uninstalled importlib-metadata-2.0.0


In [2]:
import tensorflow as tf
print(tf.__version__)

2.9.1


In [5]:
scalar = tf.constant(7)
print(scalar)
print(scalar.ndim) #dimension

tf.Tensor(7, shape=(), dtype=int32)
0


In [6]:
vector = tf.constant([10,10])
print(vector)
print(vector.ndim) #dimension

tf.Tensor([10 10], shape=(2,), dtype=int32)
1


In [7]:
matrix = tf.constant([[10,7],[7,10]])
print(matrix)
print(matrix.ndim)

tf.Tensor(
[[10  7]
 [ 7 10]], shape=(2, 2), dtype=int32)
2


In [8]:
another_matrix = tf.constant([[10.,7.],[13.,3.],[8.,9.]],dtype=tf.float16) #specyfikacja typu parametrów
print(another_matrix)
print(another_matrix.ndim)

tf.Tensor(
[[10.  7.]
 [13.  3.]
 [ 8.  9.]], shape=(3, 2), dtype=float16)
2


In [10]:
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
print(tensor)
print(tensor.ndim)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]], shape=(3, 2, 3), dtype=int32)
3


In [ ]:
#Scalar - a single number
#Vector - a number with direction
#Matrix - a 2-dimensional array of numbers
#Tensor: an n-dimensional array of numbers (n - any number, scalar = 0-dim tensor, vector = 1-dim tensor)

In [14]:
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
print(changeable_tensor)
print(unchangeable_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>
tf.Tensor([10  7], shape=(2,), dtype=int32)


In [15]:
changeable_tensor[0] = 7 #error

TypeError: 'ResourceVariable' object does not support item assignment

In [17]:
changeable_tensor[0].assign(7)
print(changeable_tensor)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>


In [18]:
unchangeable_tensor[0] = 7 #error

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [19]:
unchangeable_tensor[0].assign(7)
print(unchangeable_tensor)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [20]:
#tf.Variable can be changed by .assign()
#tf.constant can't be changed 

In [22]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [24]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [25]:
random_1, random_2, random_1 == random_2

#true because they are created on the same seed

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [26]:
#we should shuffle numbers because order in which information are taken to model, can affect output and result of created model

In [30]:
not_shuffled = tf.constant([[10,7],
                           [3,4],
                            [2,5]])
print(not_shuffled)
print(not_shuffled.ndim)

tf.Tensor(
[[10  7]
 [ 3  4]
 [ 2  5]], shape=(3, 2), dtype=int32)
2


In [31]:
tf.random.shuffle(not_shuffled) #tf.random.shuffle(variable)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]])>

In [39]:
tf.random.shuffle(not_shuffled, seed=42)  #change each time

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]])>

In [50]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)  #doesn't change 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]])>

In [51]:
#tf.random.set_seed(a)  global level of random seed
#tf.random.shuffle(...,seed=a) operation level of random seed

In [52]:
tf.ones([10,7])  #tf.ones(shape=(10,7))  numpy array

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [53]:
tf.zeros([10,7])  #tf.zeros(shape=(10,7))  numpy array

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [54]:
#turn numpy array into tensor
#difference between NumPy array and TensorFlow tensors is that tensors can be run on a GPU 

In [57]:
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [58]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [69]:
B = tf.constant(numpy_A, shape=[2,3,4])
B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [62]:
#shape can be changed, but always has to be the same after multiplying (1*24 = 24, 2*3*4 = 24)

In [63]:
#shape     the length of each of the dimensions of a tensor    tensor.shape
#rank      the number of tensor dimensions                     tensor.ndim
#size      the total number of items in the tensor             tf.size(tensor)

In [70]:
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [66]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [67]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [74]:
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions (rank): ", rank_4_tensor.ndim)
print("Shape of tensor: ",rank_4_tensor.shape)
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements in tensor: ", tf.size(rank_4_tensor))
print("Total number of elements in tensor: ", tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements in tensor:  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in tensor:  120


In [75]:
#tensors can be indexed like python list

In [76]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [79]:
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [82]:
rank_2_tensor = tf.constant([[10,7],[3,4]])
print(rank_2_tensor)
print(rank_2_tensor.ndim)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)
2


In [83]:
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

In [84]:
#add extra dimension t oout rank 2 tensor 

In [85]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [86]:
tf.expand_dims(rank_2_tensor, axis=-1) #expand last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

In [87]:
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]])>

In [88]:
#basic operations on tensors

In [90]:
tensor = tf.constant([[10,7],[3,4]])
tensor + 10  #tensor is unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 14],
       [ 6,  8]])>

In [92]:
tensor * 3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 21],
       [ 9, 12]])>

In [93]:
tensor - 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  2],
       [-2, -1]])>

In [94]:
#we can use built-in function in tf, for example:
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [96]:
tensor #unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [97]:
#matrix multiplication in tensorflow   tf.matmul - tf.matrixmultiplication

In [98]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [100]:
matrix_1 = tf.constant([[1,2,5],[7,2,1],[3,3,3]])
matrix_2 = tf.constant([[3,5],[6,7],[1,8]])
print(matrix_1.shape)
print(matrix_2.shape)
tf.matmul(matrix_1, matrix_2)

(3, 3)
(3, 2)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

In [102]:
tensor_1 = tf.constant([[1,2],[3,4],[5,6]])
tensor_2 = tf.constant([[7,8],[9,10],[11,12]])
print(tensor_1.shape)
print(tensor_2.shape)
tf.matmul(tensor_1, tensor_2)

(3, 2)
(3, 2)


InvalidArgumentError: Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]

In [109]:
tf.reshape(tensor_2, shape=(2,3))
print(tensor_2)

tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)


In [112]:
tf.matmul(tensor_1, tf.reshape(tensor_2, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [115]:
tensor_1, tf.transpose(tensor_1), tf.reshape(tensor_1, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>)

In [116]:
#changing tensors datatype

In [122]:
B = tf.constant([1.7,7.4])
print(B.dtype)

<dtype: 'float32'>


In [120]:
C = tf.constant([7,10])
print(C.dtype)

<dtype: 'int32'>


In [123]:
D = tf.cast(B, dtype=tf.float16) #changing on 16 bits (reducing precision)
print(D.dtype)

<dtype: 'float16'>


In [124]:
E = tf.cast(C, dtype=tf.float32)
print(E.dtype)

<dtype: 'float32'>


In [125]:
#get absolute values
D = tf.constant([-7, -10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

In [126]:
#create random tensor with values between 0, 100 of size 50
E = tf.constant(np.random.randint(0,100, size=50))
print(E)

tf.Tensor(
[81 13 95 88 92 61 87 11 17 18 89  5 30 69 69 21 45  7  5 72 38 74 18 38
 52 40 30 33 93 88  4 20 58 21 22 46 22 88 39 26 19 82 42 28 44 35 53 78
 66 57], shape=(50,), dtype=int32)


In [127]:
#find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [128]:
#find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=95>

In [133]:
#find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=46>

In [132]:
#find the sum of tensor
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2329>

In [176]:
#find the squared 
H = tf.range(1, 10)
H
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [179]:
#find the squareroot
tf.math.sqrt(tf.cast(H, tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [180]:
#find the log
tf.math.log(tf.cast(H, tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [145]:
pip install --upgrade tensorflow-probability

Note: you may need to restart the kernel to use updated packages.


In [146]:
import tensorflow_probability as tfp

In [147]:
#find the variance
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int32, numpy=790>

In [152]:
# or like this 
tf.math.reduce_variance(tf.cast(E, tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=790.1236>

In [150]:
#find the standart deviation, need to be float32, std^2 = var 
tf.math.reduce_std(tf.cast(E, tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.109137>

In [151]:
#find the positional maximum and minimum

In [155]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [156]:
tf.argmax(F) #index of maximum

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [157]:
tf.argmin(F) #index of minimum

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [158]:
F[tf.argmax(F)] #value of max

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [159]:
F[tf.argmin(F)] #value of min

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [163]:
#squeezing a tensor (removing all single dimension)

In [167]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [168]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [171]:
G_squeezed = tf.squeeze(G)
print(G_squeezed)
print(G_squeezed.shape)

tf.Tensor(
[0.6645621  0.44100678 0.3528825  0.46448255 0.03366041 0.68467236
 0.74011743 0.8724445  0.22632635 0.22319686 0.3103881  0.7223358
 0.13318717 0.5480639  0.5746088  0.8996835  0.00946367 0.5212307
 0.6345445  0.1993283  0.72942245 0.54583454 0.10756552 0.6767061
 0.6602763  0.33695042 0.60141766 0.21062577 0.8527372  0.44062173
 0.9485276  0.23752594 0.81179297 0.5263394  0.494308   0.21612847
 0.8457197  0.8718841  0.3083862  0.6868038  0.23764038 0.7817228
 0.9671384  0.06870162 0.79873943 0.66028714 0.5871513  0.16461694
 0.7381023  0.32054043], shape=(50,), dtype=float32)
(50,)


In [ ]:
#one-hot encoding tensors

In [172]:
#create a list of indices
some_list = [0,1,2,3] #let say: red, green, blue, purple

#one hot encode our list of indices
tf.one_hot(some_list, depth=4) #depth is equal to len(some_list)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [174]:
tf.one_hot(some_list, depth=4, on_value="Y", off_value="N") #change numbers to words

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Y', b'N', b'N', b'N'],
       [b'N', b'Y', b'N', b'N'],
       [b'N', b'N', b'Y', b'N'],
       [b'N', b'N', b'N', b'Y']], dtype=object)>

In [181]:
#tensors and numpy

In [182]:
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [184]:
np.array(J), type(np.array(J)) #convert tensor to numpy array

(array([ 3.,  7., 10.]), numpy.ndarray)

In [185]:
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [187]:
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)